DROP TABLE IF EXISTS city;

CREATE TABLE IF NOT EXISTS city (
    id SERIAL PRIMARY KEY,
    id_province VARCHAR(255) NOT NULL,
    city_name VARCHAR(255) UNIQUE NOT NULL,
    city_code VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL
);
